spring:
  application:
    name: ms-rapports
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://localhost:3306/bordereau_bd
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate

server:
  servlet:
    context-path: /backend
  port: 8090

logging:
  level:
    tech.chillo: TRACE

